In [1]:
import numpy as np
import pandas as pd

BÀI 1

In [2]:
arr_1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 3x3:\n", arr_1)
print("Tất cả phần tử đều khác 0?:", np.all(arr_1 != 0))

Mảng 3x3:
 [[ 3 10  6]
 [18 10 12]
 [16  5  0]]
Tất cả phần tử đều khác 0?: False


BÀI 2

In [3]:
arr_2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 3x3:\n", arr_2)
print("Có tồn tại phần tử khác 0?:", np.any(arr_2 != 0))

Mảng 3x3:
 [[17  5  4]
 [ 6  9  9]
 [14  2 16]]
Có tồn tại phần tử khác 0?: True


BÀI 3

In [4]:
a1, b1 = np.array([1, 5, 9]), np.array([2, 5, 8])
print("1D Greater:", np.greater(a1, b1))
print("1D Greater Equal:", np.greater_equal(a1, b1))
print("1D Less:", np.less(a1, b1))
print("1D Less Equal:", np.less_equal(a1, b1))

# So sánh 2 chiều
a2, b2 = np.array([[1, 2], [3, 4]]), np.array([[1, 3], [2, 4]])
print("\n2D Greater:\n", np.greater(a2, b2))
print("2D Greater Equal:\n", np.greater_equal(a2, b2))
print("2D Less:\n", np.less(a2, b2))
print("2D Less Equal:\n", np.less_equal(a2, b2))

1D Greater: [False False  True]
1D Greater Equal: [False  True  True]
1D Less: [ True False False]
1D Less Equal: [ True  True False]

2D Greater:
 [[False False]
 [ True False]]
2D Greater Equal:
 [[ True False]
 [ True  True]]
2D Less:
 [[False  True]
 [False False]]
2D Less Equal:
 [[ True  True]
 [False  True]]


BÀI 4

In [6]:
# Bài 4: Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
arr_ones = np.ones(10)
arr_zeros = np.zeros(10)
arr_fives = np.full(10, 5)

arr_4 = np.concatenate((arr_ones, arr_zeros, arr_fives))
print("Mảng kết quả:\n", arr_4)

Mảng kết quả:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


BÀI 5

In [7]:
# Bài 5: Viết chương trình tạo mảng số nguyên chẵn từ [30, 70]
arr_5 = np.arange(30, 71, 2)
print("Mảng số chẵn [30, 70]:\n", arr_5)

Mảng số chẵn [30, 70]:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


BÀI 6

In [8]:
# Bài 6: Viết chương trình tạo ma trận đơn vị 3 x 3
# (đường chéo chính bằng 1, các phần tử còn lại 0)
arr_6 = np.identity(3)
print("Ma trận đơn vị 3x3:\n", arr_6)

Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


BÀI 7

In [9]:
# Bài 7: Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55].
# In các giá trị ngoại trừ phần tử đầu và cuối
arr_7 = np.random.randint(15, 56, size=10)
print("Mảng ban đầu:\n", arr_7)
print("Ngoại trừ phần tử đầu và cuối:\n", arr_7[1:-1])

Mảng ban đầu:
 [39 27 37 42 34 23 28 33 25 52]
Ngoại trừ phần tử đầu và cuối:
 [27 37 42 34 23 28 33 25]


BÀI 8

In [10]:
# Bài 8: Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20]
# và đổi dấu những số nằm trong khoảng [9, 15]
arr_8 = np.random.randint(0, 21, size=20)
print("Mảng ban đầu:\n", arr_8)

# Lọc và đổi dấu
arr_8[(arr_8 >= 9) & (arr_8 <= 15)] *= -1
print("Mảng sau khi đổi dấu:\n", arr_8)

Mảng ban đầu:
 [ 7 11  8 10 17 17 18  1 14  7  6 10 18 13 12  2  7  2  2  5]
Mảng sau khi đổi dấu:
 [  7 -11   8 -10  17  17  18   1 -14   7   6 -10  18 -13 -12   2   7   2
   2   5]


BAI 9

In [11]:
# Bài 9: Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]
arr_9 = np.arange(10, 22).reshape(3, 4)
print("Ma trận 3x4:\n", arr_9)

Ma trận 3x4:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


BÀI 10


In [12]:
# Bài 10: Viết chương trình tạo ma trận 10 x 10,
# các phần tử ở biên có giá trị 1, các phần tử bên trong có giá trị 0
arr_10 = np.ones((10, 10))
arr_10[1:-1, 1:-1] = 0
print("Ma trận 10x10:\n", arr_10)

Ma trận 10x10:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


BÀI 11

In [13]:
# Bài 11: Viết chương trình tạo ma trận 5 x 5,
# các phần tử ở đường chéo chính là 1, 2, 3, 4, 5
arr_11 = np.diag([1, 2, 3, 4, 5])
print("Ma trận 5x5:\n", arr_11)

Ma trận 5x5:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


BÀI 12

In [14]:
# Bài 12: Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột.
arr_12 = np.random.randint(1, 10, size=(3, 3, 3))
print("Mảng 3x3x3:\n", arr_12)

# Tổng theo các trục (axis) khác nhau
print("\nTổng theo trục 1 (cột trong ma trận 2D):\n", np.sum(arr_12, axis=1))
print("\nTổng theo trục 2 (dòng trong ma trận 2D):\n", np.sum(arr_12, axis=2))

Mảng 3x3x3:
 [[[9 7 2]
  [2 4 5]
  [4 1 2]]

 [[1 2 6]
  [9 6 8]
  [3 7 2]]

 [[9 6 6]
  [1 1 4]
  [7 8 1]]]

Tổng theo trục 1 (cột trong ma trận 2D):
 [[15 12  9]
 [13 15 16]
 [17 15 11]]

Tổng theo trục 2 (dòng trong ma trận 2D):
 [[18 11  7]
 [ 9 23 12]
 [21  6 16]]


BÀI 13

In [15]:
# Bài 13: Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)
v1 = np.random.rand(10)
v2 = np.random.rand(10)
print("Inner product:", np.dot(v1, v2))

Inner product: 2.0691196740024034


BÀI 14

In [16]:
# Bài 14: Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên.
# Thêm vector y vào từng dòng của ma trận A
A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)

print("Ma trận A:\n", A)
print("Vector y:", y)
# Nhờ cơ chế broadcasting, numpy sẽ tự động cộng vector y vào mỗi dòng
print("Kết quả A + y:\n", A + y)

Ma trận A:
 [[7 5 3]
 [1 7 5]
 [3 8 7]
 [8 3 2]]
Vector y: [7 9 8]
Kết quả A + y:
 [[14 14 11]
 [ 8 16 13]
 [10 17 15]
 [15 12 10]]


BÀI 15

In [17]:
# Bài 15: Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series:
# [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


BÀI 16

In [18]:
# Bài 16: Pandas chuyển đổi cột đầu tiên thành Series
# (Thuộc tính .ix đã bị Pandas loại bỏ, thay bằng .iloc)
df_16 = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})

series_col1 = df_16.iloc[:, 0]
print("1st column as a Series:\n", series_col1)

1st column as a Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


BÀI 17

In [19]:
# Bài 17: Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên
df_17 = pd.DataFrame(np.random.randint(1, 20, size=(4, 3)), columns=['Col1', 'Col2', 'Col3'])
print("DataFrame ban đầu:\n", df_17)

df_sorted = df_17.sort_values(by='Col1')
print("\nSắp xếp theo Col1:\n", df_sorted)

DataFrame ban đầu:
    Col1  Col2  Col3
0     2     9     5
1    13    11    11
2    11     7    17
3     4    15    14

Sắp xếp theo Col1:
    Col1  Col2  Col3
0     2     9     5
3     4    15    14
2    11     7    17
1    13    11    11


BÀI 18

In [20]:
# Bài 18: Pandas thay đổi index của một Series (dùng pandas.reindex)
s_18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Original Data Series:\n", s_18)

s_reindexed = s_18.reindex(['B', 'A', 'C', 'D', 'E'])
print("\nData Series after changing the order of index:\n", s_reindexed)

Original Data Series:
 A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series after changing the order of index:
 B    2
A    1
C    3
D    4
E    5
dtype: int64


BÀI 19

In [21]:
# Bài 19: Tìm những phần tử trong Series x mà không có trong Series y (hàm isin)
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# Dùng toán tử ~ để lấy phần bù của hàm isin
diff = sr1[~sr1.isin(sr2)]
print("Items of sr1 not present in sr2:\n", diff)

Items of sr1 not present in sr2:
 0    1
2    3
4    5
dtype: int64


BÀI 20

In [22]:
# Bài 20: Phép toán numpy.union1d, numpy.intersect1d (hội, giao)
# trên 2 Series ngẫu nhiên có 20 phần tử
sx = pd.Series(np.random.randint(1, 50, size=20))
sy = pd.Series(np.random.randint(1, 50, size=20))

print("Hội (Union):", np.union1d(sx, sy))
print("Giao (Intersection):", np.intersect1d(sx, sy))

Hội (Union): [ 1  3  4  5  6  7  9 10 12 13 14 16 17 18 21 23 26 27 33 34 35 36 37 39
 42 43 45 47 49]
Giao (Intersection): [ 5  6  9 10 21 39 47]


BÀI 21

In [23]:
# Bài 21: Thêm series y vào series x theo chiều dọc, chiều ngang
# (Hàm .append() của Series đã bị gỡ bỏ ở phiên bản mới, ta dùng pd.concat)
series_x = pd.Series([0, 1, 2, 7, 8, 9])
series_y = pd.Series(['p', 'q', 'r', 'w', 'x', 'y'])

print("Chiều dọc (Vertical):\n", pd.concat([series_x, series_y], axis=0, ignore_index=True))
print("\nChiều ngang (Horizontal):\n", pd.concat([series_x, series_y], axis=1))

Chiều dọc (Vertical):
 0     0
1     1
2     2
3     7
4     8
5     9
6     p
7     q
8     r
9     w
10    x
11    y
dtype: object

Chiều ngang (Horizontal):
    0  1
0  0  p
1  1  q
2  2  r
3  7  w
4  8  x
5  9  y


BÀI 22

In [24]:
# Bài 22: Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_22 = pd.DataFrame(exam_data, index=labels)
print("DataFrame exam_data:\n", df_22)

DataFrame exam_data:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


BÀI 23

In [25]:
# Bài 23: Từ bài 22, cho biết 3 dòng đầu tiên
print("3 dòng đầu tiên:\n", df_22.head(3))

3 dòng đầu tiên:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


BÀI 24

In [26]:
# Bài 24: Từ bài 22, chọn cột ‘name’ và ‘score’
print("Cột name và score:\n", df_22[['name', 'score']])

Cột name và score:
         name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


BÀI 25

In [27]:
# Bài 25: Từ bài 22, chọn những dòng có attempts > 2
print("Dòng có attempts > 2:\n", df_22[df_22['attempts'] > 2])

Dòng có attempts > 2:
       name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


BÀI 26

In [28]:
# Bài 26: Từ bài 22, cho biết số dòng, số cột của DataFrame
print("Kích thước (dòng, cột) của DataFrame:", df_22.shape)

Kích thước (dòng, cột) của DataFrame: (10, 4)


BÀI 27

In [29]:
# Bài 27: Từ bài 22, cho biết những dòng có score là NaN (hàm isnull)
print("Dòng có score là NaN:\n", df_22[df_22['score'].isnull()])

Dòng có score là NaN:
     name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


BÀI 28

In [30]:
# Bài 28: Từ bài 22, cho biết những dòng có score trong khoảng (15, 20)
# Hàm between mặc định sẽ bao gồm cả giá trị 15 và 20
print("Dòng có score trong khoảng (15, 20):\n", df_22[df_22['score'].between(15, 20)])

Dòng có score trong khoảng (15, 20):
         name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


BÀI 29

In [31]:
# Bài 29: Từ bài 22, cho biết những dòng có attempt > 2 và score trong khoảng (15, 20)
condition = (df_22['attempts'] > 2) & (df_22['score'].between(15, 20))
print("Dòng thỏa mãn điều kiện:\n", df_22[condition])

Dòng thỏa mãn điều kiện:
       name  score  attempts qualify
f  Michael   20.0         3     yes


BÀI 30

In [32]:
# Bài 30: Từ bài 22, thay đổi giá trị dòng ‘d’, cột score là 19 (hàm loc)
df_22.loc['d', 'score'] = 19
print("DataFrame sau khi sửa điểm dòng 'd':\n", df_22)

DataFrame sau khi sửa điểm dòng 'd':
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
